### ISSUE TITLE
動画ストリーミング機能の追加

### ISSUE THREAD

**Issue by Soonki** [Soonki/drone_contest#8]
https://qiita.com/MuAuan/items/b3abd4cff2f39aa1f2d0

**Comment by uchiwacube** [comment]
進捗メモ：Soonkiさんサジェストのサイトだと上手くいかなかったので下のサイトを参考に入れました。
https://qiita.com/xeno1991/items/e32e52c688d969d182e2
同一回線上でカメラ映像を見ることができました。
方針としては
1.サーバー立てのコマンドをプロポのスイッチで実行
か
2.試合開始前にサーバーを立てて置く
のかどちらかにするつもりです。昨年は1の方法だったらしいのでfeature/streamingを作って試します。

**Comment by Soonki** [comment]
@uchiwacube 
ブランチ名は`feature#8-streaming`的な感じでissue番号入れた方がええで

**Comment by uchiwacube** [comment]
了解です変えました！

**Comment by uchiwacube** [comment]
進捗メモ：pythonプログラムからサーバーを起動、終了できるように。
⇛それをクラス化して、実際にプロポを入力して動作確認まで終わりました。
ストリーミングが2秒くらい遅れるのと終了指示が届くまで10秒以上かかるので、画面のfpsを下げるなどして軽量化を狙いつつmain.pyで使えるようにします。（main.pyの動作確認がまだなので確認後に）

**Comment by Soonki** [comment]
@uchiwacube 
多分、`main.py`までの実装をこのブランチでやるのは長すぎやから、クラスとそのテスト作ったら、プルリクだしたらいいと思う。別に

- streamingクラスの`main.py`への適用
- main.pyの動作確認及び修正

ってissueたてたほうがいいと思う。変更が多くなると何が変わったかわからんなるから

**Comment by uchiwacube** [comment]
お気づきになるのがお早い・・・
featureはほぼ人毎に分けるものかと思ってました。細かい方が後で見た時わかりやすいっすね。やっていきます。

**Comment by Soonki** [comment]
@uchiwacube 
featureは機能ごとの切り分けやから、プルリクのときにどこ変更したかわかる程度じゃないとあかんねん。仕事やと一日に３つブランチ切って３つプルリクあげるくらいのペース。

**Comment by uchiwacube** [comment]
@Soonki プルリクそんな頻繁にするんですね。1日毎にはしないと思いますがある程度細かめにはします。
